/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cfi027.pkg2023.swing.aula.pkg2;

import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class Tela extends javax.swing.JFrame {
  double preco=0;

  /**
   * Creates new form Tela
   */
  public Tela() {
    initComponents();
    bgSanduiche.add(rbEgg);
    bgSanduiche.add(rbChees);
    bgSanduiche.add(rbHam);
    bgSanduiche.add(rbMonstro);

    
   
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    bgSanduiche = new javax.swing.ButtonGroup();
    jPanel1 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jPanel2 = new javax.swing.JPanel();
    rbHam = new javax.swing.JRadioButton();
    rbChees = new javax.swing.JRadioButton();
    rbEgg = new javax.swing.JRadioButton();
    rbMonstro = new javax.swing.JRadioButton();
    jLabel3 = new javax.swing.JLabel();
    jPanel3 = new javax.swing.JPanel();
    jLabel4 = new javax.swing.JLabel();
    cbQueijo = new javax.swing.JCheckBox();
    cbBacon = new javax.swing.JCheckBox();
    cbOvo = new javax.swing.JCheckBox();
    cbMonstro = new javax.swing.JCheckBox();
    btnPreco = new javax.swing.JButton();
    btnLimpar = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jPanel1.setBackground(new java.awt.Color(204, 153, 0));

    jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
    jLabel1.setText("Sanduicheria Chique da CFI027");

    jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/sauduiche.png"))); // NOI18N
    jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    jLabel2.setPreferredSize(new java.awt.Dimension(538, 500));

    rbHam.setText("Hamburguer");
    rbHam.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        rbHamActionPerformed(evt);
      }
    });

    rbChees.setText("ChesseBurguer");

    rbEgg.setText("EggBurguer");

    rbMonstro.setText("Picanha Banco Egg Cheese Burguer Monstro");

    jLabel3.setText("Sanduiches");

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addGap(70, 70, 70)
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel3)
          .addGroup(jPanel2Layout.createSequentialGroup()
            .addComponent(rbHam)
            .addGap(48, 48, 48)
            .addComponent(rbChees)
            .addGap(50, 50, 50)
            .addComponent(rbEgg)
            .addGap(95, 95, 95)
            .addComponent(rbMonstro)))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addGap(6, 6, 6)
        .addComponent(jLabel3)
        .addGap(18, 18, 18)
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(rbHam)
          .addComponent(rbChees)
          .addComponent(rbEgg)
          .addComponent(rbMonstro))
        .addContainerGap(39, Short.MAX_VALUE))
    );

    jLabel4.setText("Adicionais:");

    cbQueijo.setText("Queijo");

    cbBacon.setText("Bacon");

    cbOvo.setText("Ovo");

    cbMonstro.setText("Monstro");

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel3Layout.createSequentialGroup()
        .addGap(77, 77, 77)
        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel3Layout.createSequentialGroup()
            .addComponent(cbQueijo)
            .addGap(53, 53, 53)
            .addComponent(cbBacon)
            .addGap(65, 65, 65)
            .addComponent(cbOvo)
            .addGap(87, 87, 87)
            .addComponent(cbMonstro))
          .addComponent(jLabel4))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel3Layout.setVerticalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel3Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel4)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(cbQueijo)
          .addComponent(cbBacon)
          .addComponent(cbOvo)
          .addComponent(cbMonstro))
        .addContainerGap(45, Short.MAX_VALUE))
    );

    btnPreco.setText("Preço");
    btnPreco.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnPrecoActionPerformed(evt);
      }
    });

    btnLimpar.setText("Limpar");
    btnLimpar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnLimparActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(125, 125, 125))
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
          .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 895, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        .addGap(0, 20, Short.MAX_VALUE))
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(90, 90, 90)
        .addComponent(btnPreco)
        .addGap(50, 50, 50)
        .addComponent(btnLimpar)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btnPreco)
          .addComponent(btnLimpar))
        .addContainerGap(178, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 220, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void rbHamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbHamActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_rbHamActionPerformed

  private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
rbHam.setSelected(true);
cbQueijo.setSelected(false);
cbBacon.setSelected(false);
cbOvo.setSelected(false);
cbMonstro.setSelected(false);
preco=0;
  
  }//GEN-LAST:event_btnLimparActionPerformed

  private void btnPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrecoActionPerformed

if (rbHam.isSelected()){
  preco=13.50;
}
if (rbChees.isSelected()){
  preco=15.20;
}
if (rbEgg.isSelected()){
  preco=14.30;
}
if (rbMonstro.isSelected()){
  preco=25.00;
}
if (cbMonstro.isSelected()){
  preco=preco+12;
}
if (cbOvo.isSelected()){
  preco=preco+3;
}
if (cbBacon.isSelected()){
  preco=preco+4;
}
if (cbQueijo.isSelected()){
  preco=preco+3.8;
}

 JOptionPane.showMessageDialog (null, "Valor a Pagar "+ Double.toString(preco));

  }//GEN-LAST:event_btnPrecoActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new Tela().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.ButtonGroup bgSanduiche;
  private javax.swing.JButton btnLimpar;
  private javax.swing.JButton btnPreco;
  private javax.swing.JCheckBox cbBacon;
  private javax.swing.JCheckBox cbMonstro;
  private javax.swing.JCheckBox cbOvo;
  private javax.swing.JCheckBox cbQueijo;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JRadioButton rbChees;
  private javax.swing.JRadioButton rbEgg;
  private javax.swing.JRadioButton rbHam;
  private javax.swing.JRadioButton rbMonstro;
  // End of variables declaration//GEN-END:variables
}
